#!/bin/sh
#
# @name NDT Tilting
#
# @type Tilting Multirotor
# @class Copter
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output MAIN5 motor 5
# @output MAIN6 motor 6
# @output MAIN6 motor 7
# @output MAIN6 motor 8
# @output MAIN6 motor 9
# @output MAIN6 motor 10
# @output MAIN6 motor 11
# @output MAIN6 motor 12
#
# @output AUX1 motor 1
# @output AUX2 motor 2
# @output AUX3 motor 3
# @output AUX4 motor 4
#
# @maintainer Salvatore Marcellini <salvatore.marcellini@gmail.com>
#

. ${R}etc/init.d/rc.mc_defaults


param set-default MAV_TYPE 14

param set-default SYS_CTRL_ALLOC 1 #dynamic allocation
param set-default CA_AIRFRAME 11 #Tilting Multirotor
param set-default CA_TILTING_TYPE 1 #Omnidirectional tilting drone


# Set all 8 channels
set PWM_OUT 12345678
set PWM_AUX_OUT 1234
param set-default CA_ROTOR_COUNT 8
param set-default CA_SV_TL_COUNT 4

param set-default CA_ROTOR0_PX 0.35 #M1 CW
param set-default CA_ROTOR0_PY 0.35
param set-default CA_ROTOR0_PZ 0.05
param set-default CA_ROTOR0_KM -0.05

param set-default CA_ROTOR1_PX -0.35 #M2 CCW
param set-default CA_ROTOR1_PY 0.35
param set-default CA_ROTOR1_PZ 0.05
param set-default CA_ROTOR1_KM 0.05

param set-default CA_ROTOR2_PX -0.35  #M3 CW
param set-default CA_ROTOR2_PY -0.35
param set-default CA_ROTOR2_PZ 0.05
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX 0.35 #M4 CCW
param set-default CA_ROTOR3_PY -0.35
param set-default CA_ROTOR3_PZ 0.05
param set-default CA_ROTOR3_KM 0.05

param set-default CA_ROTOR4_PX -0.35 #M5 CW
param set-default CA_ROTOR4_PY 0.35
param set-default CA_ROTOR4_PZ -0.05
param set-default CA_ROTOR4_KM -0.05

param set-default CA_ROTOR5_PX 0.35 #M6 CCW
param set-default CA_ROTOR5_PY 0.35
param set-default CA_ROTOR5_PZ -0.05
param set-default CA_ROTOR5_KM 0.05

param set-default CA_ROTOR6_PX 0.35  #M7 CW
param set-default CA_ROTOR6_PY -0.35
param set-default CA_ROTOR6_PZ -0.05
param set-default CA_ROTOR6_KM -0.05

param set-default CA_ROTOR7_PX -0.35 #M8 CCW
param set-default CA_ROTOR7_PY -0.35
param set-default CA_ROTOR7_PZ -0.05
param set-default CA_ROTOR7_KM 0.05



